### ISSUE TITLE
CORS Policy Issue

### ISSUE THREAD

**Issue by shailshin** [rmraya/TMEngine#4]
Hi Team,

From our ReactJS UI we are calling REST API but we are not receiving responses from API due to CORS policy issues.
When we tried to create memory, this gets created in database but the response is not coming and throws error.

Can you please provide us any reference where or in which file we need to fix this issue.

Thanks & Regards,
Shailesh

**Comment by rmraya** [comment]
Hello,

You should use [RemoteTM](https://github.com/rmraya/RemoteTM) instead. RemoteTM already has a web interface and is based on more recent versions of [OpenXLIFF Filters](https://github.com/rmraya/OpenXLIFF) and [Swordfish](https://github.com/rmraya/Swordfish).

**Comment by shailshin** [comment]
Thanks! We are using RemoteTM.
